name: jera_muvver
description: Muvver is an application designed for testing.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: "TitilliumWeb"
      fonts:
        - asset: fonts/TitilliumWeb/TitilliumWeb-Regular.ttf
          weight: 400
        - asset: fonts/TitilliumWeb/TitilliumWeb-SemiBold.ttf
          weight: 600
        - asset: fonts/TitilliumWeb/TitilliumWeb-Bold.ttf
          weight: 700

  assets:
    - assets/images
